// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package ttssqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Username  string
	Salt      string
	Password  sql.NullString
	Email     sql.NullString
	Confirmed sql.NullBool
	CreatedAt time.Time
}
