// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package ttssqlc

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
SELECT id, username, salt, password, email, confirmed, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Salt,
		&i.Password,
		&i.Email,
		&i.Confirmed,
		&i.CreatedAt,
	)
	return i, err
}
