/*
 * Tiny tracker
 *
 * Tiny tracker server API
 *
 * API version: 1.0.0
 * Contact: anmi.asm@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CurrentUser struct {

	Username string `json:"username,omitempty"`

	Email string `json:"email,omitempty"`
}

// AssertCurrentUserRequired checks if the required fields are not zero-ed
func AssertCurrentUserRequired(obj CurrentUser) error {
	return nil
}

// AssertRecurseCurrentUserRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CurrentUser (e.g. [][]CurrentUser), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCurrentUserRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCurrentUser, ok := obj.(CurrentUser)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCurrentUserRequired(aCurrentUser)
	})
}
